version: '3'

services:
  #
  # Proxy - HTTP entrypoint
  proxy:
    image: ${COMPOSE_PROJECT_NAME}_proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}_entrypoint
    restart: unless-stopped
    expose:
      - "80"
    build:
      context: ./.proxy
    environment:
      - DHPARAM_GENERATION=false
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${NGINX_LOGS:-./app/logs}:/var/log/nginx
      - ${WORDPRESS_DATA:-./app/wordpress}:/var/www/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - https-revproxy
      - wordpress
  
  #
  # Application & DB
  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.4-fpm-alpine}
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
      - proxy
    expose: 
      - "9000"
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mariadb}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
    volumes:
      - ${WORDPRESS_DATA:-./app/wordpress}:/var/www/html    
    networks:
      - wordpress
  
  # DB
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    restart: unless-stopped
    expose:
      - "3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    volumes:
      - ${MARIADB_DATA:-./app/mariadb}:/var/lib/mysql
    networks:
      - wordpress
  
  # Adminer
  adminer:
    image: adminer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    restart: unless-stopped
    depends_on:
      - mariadb
      - proxy
    links:
      - mariadb
    expose:
      - "8080"
    networks: 
      - wordpress

  # Toolbox WP-CLI & composer container
  toolbox:
    container_name: ${COMPOSE_PROJECT_NAME}_toolbox
    restart: unless-stopped
    build:
      context: ./.toolbox
    depends_on:
      - wordpress
      - mariadb
      - proxy
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mariadb}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
      # Site specific variables
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - WORDPRESS_LOCALE={WORDPRESS_LOCALE:-en_EN}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER:-wp-admin}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD:-changeme}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL:-wp-admin@yopmail.com}
      - WORDPRESS_WEBSITE_POST_URL_STRUCTURE=${WORDPRESS_WEBSITE_POST_URL_STRUCTURE:-/%year%/%monthnum%/%day%/%postname%/}
    volumes:
      - ${WORDPRESS_DATA:-./app/wordpress}:/var/www/html 
    networks:
      - wordpress

networks:
  https-revproxy:
    external:
      name: ${APPS_NETWORK}
  wordpress: