version: '3'

services:
  #
  # Proxy - HTTP entrypoint
  proxy:
    image: ${COMPOSE_PROJECT_NAME}_proxy:latest
    container_name: proxy4${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    expose:
      - "80"
    build:
      context: ./proxy
    environment:
      - DHPARAM_GENERATION=false
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${NGINX_LOGS:-./app_logs/nginx}:/var/log/nginx
      - ${WORDPRESS_DATA:-./app_wordpress}:/var/www/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - wp-headless
      - wordpress
  
  #
  # Application & DB
  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.4-fpm-alpine}
    container_name: wordpress4${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    depends_on:
      - mariadb
      - proxy
    expose: 
      - "80"
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
    volumes:
      - ${WORDPRESS_DATA:-./app_wordpress}:/var/www/html    
    networks:
      - wordpress
  
  # DB
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mariadb4${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    expose:
      - "3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    volumes:
      - ${MARIADB_DATA:-./app_mariadb}
    networks:
      - wordpress
  
  # Adminer
  adminer:
    image: adminer:latest
    container_name: adminer4${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    links:
      - mariadb
    expose:
      - "8080"
    networks: 
      - wordpress

networks:
  wp-headless:
    external:
      name: wp-headless
  wordpress: